[package]
name = "auto_aim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.7"
log = "0.4.26"
once_cell = "1.21.1"
# dora-node-api = "0.3.10"
